<?php

use Illuminate\Database\Seeder;

class CatAuditorSeeder extends Seeder
{
	public function run()
	{
		$auditors = 
		[
			['name'=>'Alfredo Gomez'],
			['name'=>'Alma Del Carmen Ruiz'],
			['name'=>'Antonio De Jesus Castillo Montoya'],
			['name'=>'Arnulfo Gomez Izquierdo'],
			['name'=>'Arturo Ramirez Lobos'],
			['name'=>'Carlos Alberto Jimenez'],
			['name'=>'Daniel Armando Cordero'],
			['name'=>'Eduardo Coronel Díaz'],
			['name'=>'Eiber Quintaz Quiroz'],
			['name'=>'Erick Valentin Jimenez Gomez'],
			['name'=>'Ismael Colmenares Torres'],
			['name'=>'Javier Alvarado Mtz'],
			['name'=>'Javier Marban Moreno'],
			['name'=>'Jesus Daniel Alamilla Torres'],
			['name'=>'Jorge Alejandro Jimenez Gomez'],
			['name'=>'Jose Castillo Castillo'],
			['name'=>'Juan Pablo Mtz. Geronimo'],
			['name'=>'Lizbeth Narez Ventura'],
			['name'=>'Luis Felipe Peregrino Javier'],
			['name'=>'Manuel Antonio Landero Sauz'],
			['name'=>'Maria Asuncion Gonzalez Cruz'],
			['name'=>'Miguel Antonio Yamada Garcia'],
			['name'=>'Rommel Cabrera'],
			['name'=>'Sergio Arturo Hernandez Hernandez'],
			['name'=>'Patricia Alejandro Cupil'],
			['name'=>'Javier Alvarado Martinez'],
			['name'=>'Martin Emigdio Alvarado Mora'],
			['name'=>'Jose Ricardo Alvarado Valladares'],
			['name'=>'Roció Del Carmen Alvarez  Garcia'],
			['name'=>'Leonardo Arevalo Morales'],
			['name'=>'Hugo Alberto Barragan GÜemez'],
			['name'=>'Jaqueline Bautista  Reyes'],
			['name'=>'Francisco Casanova Guerrero'],
			['name'=>'Emanuel Castellanos Campos'],
			['name'=>'María Alejandra  Castillo López'],
			['name'=>'Francisco Javier Contreras  Calva'],
			['name'=>'Bernardo Contreras Montalvo'],
			['name'=>'Samuel Cordova Fuentes'],
			['name'=>'Dafne Del Carmen De La Cruz Carrillo'],
			['name'=>'Luis Enrique De La Cruz De Los Santos'],
			['name'=>'Jesus Eduardo Dominguez Angulo'],
			['name'=>'Yanet Dominguez Gomez'],
			['name'=>'Sandra Ferrer  Garcia'],
			['name'=>'Margarita Florentino Aleman'],
			['name'=>'Jose Armando Gallardo Hernandez'],
			['name'=>'Luis Mario Jeronimo Diaz'],
			['name'=>'Alfredo  Godínez  Cruz'],
			['name'=>'Rocio Gutierrez Sanchez'],
			['name'=>'Guillermo Othokani  Hernández  Salgado'],
			['name'=>'Olga Cecilia Hernandez Dominguez'],
			['name'=>'Diego Hernandez Sanchez'],
			['name'=>'Libni Mhali Javier Rodriguez'],
			['name'=>'Jorge Alejandro Jimenez Garcia'],
			['name'=>'Violeta Leyva  Burelo'],
			['name'=>'Arturo Llanos Escribano'],
			['name'=>'Jesus Gaspar Luna Dominguez'],
			['name'=>'David MagaÑa Cornelio'],
			['name'=>'Wilbert Fabian Martinez Ordaz'],
			['name'=>'Ricardo May Diaz'],
			['name'=>'Ingrid Cecilia May Reyes'],
			['name'=>'Amayrani Mediola Merinos'],
			['name'=>'Margarita Mendez Marquez'],
			['name'=>'Erick Efrain Meza Diaz'],
			['name'=>'Daria Miguel Cano'],
			['name'=>'Leobardo Morales Hernandez'],
			['name'=>'Ricardo MuÑoz Delgado'],
			['name'=>'Aurora Guadalupe MuÑoz Sanchez'],
			['name'=>'Luis Marzel Nolasco Lopez'],
			['name'=>'David Antonio Olan  Leon'],
			['name'=>'Said  Ponce  Ortega'],
			['name'=>'Claribel Pons Garcia'],
			['name'=>'Eiber Antonio  Quintas Quiroz'],
			['name'=>'Ninive Ramirez  De La Cruz'],
			['name'=>'Lorena Del Carmen Ramirez  Ramirez'],
			['name'=>'Tania Valeria Ramos Mendez'],
			['name'=>'Gustavo Adolfo Rodriguez Cedillo'],
			['name'=>'Carlos Alberto Romero Amador'],
			['name'=>'Emilio  Ruiz  Ríos'],
			['name'=>'Stephani Guadalupe Ruiz Marquez'],
			['name'=>'Flor De Li Sanchez Sanchez'],
			['name'=>'Gilberto Santos  Rodriguez'],
			['name'=>'Cesar Augusto Segura Alejandro'],
			['name'=>'Santos Torres Segovia'],
			['name'=>'David Alejandro  Valdez  Contreras'],
			['name'=>'Roberto Alonso Valenzuela Castellanos'],
			['name'=>'Rosalba Vazquez Mancillas'],
			['name'=>'Omar Isidro Vega Pulido'],
			['name'=>'Gabriel Zamora Bautista'],
			['name'=>'Luis Mario Geronimo Diaz'],
			['name'=>'Daria Moguel Cano'],
			['name'=>'Jose Luis Gordillo Cansigno'],
			['name'=>'Andres TreviÑo SaldaÑa'],
			['name'=>'Cesar Arias Roman'],
			['name'=>'Alejandra Marquez Valencia'],
			['name'=>'Gonzalo Andrade'],
			['name'=>'Valente Muñoz'],
			['name'=>'Erick Humberto Espinoza'],
			['name'=>'Jesús Emmanuel Martínez'],
			['name'=>'Melchor Gonzales V.'],
			['name'=>'Valente Juarez Muñoz']
		];

		foreach($auditors as $auditor)
		{
			App\CatAuditor::create($auditor);
		}
	}
}
