<?php

use Illuminate\Database\Seeder;

class CatDeductionSeeder extends Seeder
{
	public function run()
	{
		$deductions = [
			['id' => '001', 'description' => 'Seguridad social', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '002', 'description' => 'ISR', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '003', 'description' => 'Aportaciones a retiro, cesantía en edad avanzada y vejez.', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '004', 'description' => 'Otros', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '005', 'description' => 'Aportaciones a Fondo de vivienda', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '006', 'description' => 'Descuento por incapacidad', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '007', 'description' => 'Pensión alimenticia', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '008', 'description' => 'Renta', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '009', 'description' => 'Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '010', 'description' => 'Pago por crédito de vivienda', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '011', 'description' => 'Pago de abonos INFONACOT', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '012', 'description' => 'Anticipo de salarios', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '013', 'description' => 'Pagos hechos con exceso al trabajador', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '014', 'description' => 'Errores', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '015', 'description' => 'Pérdidas', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '016', 'description' => 'Averías', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '017', 'description' => 'Adquisición de artículos producidos por la empresa o establecimiento', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '018', 'description' => 'Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '019', 'description' => 'Cuotas sindicales', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '020', 'description' => 'Ausencia (Ausentismo)', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '021', 'description' => 'Cuotas obrero patronales', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '022', 'description' => 'Impuestos Locales', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '023', 'description' => 'Aportaciones voluntarias', 'validity_start' => '2016-11-01', 'validity_end' => NULL],
			['id' => '024', 'description' => 'Ajuste en Gratificación Anual (Aguinaldo) Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '025', 'description' => 'Ajuste en Gratificación Anual (Aguinaldo) Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '026', 'description' => 'Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '027', 'description' => 'Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '028', 'description' => 'Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '029', 'description' => 'Ajuste en Fondo de ahorro Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '030', 'description' => 'Ajuste en Caja de ahorro Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '031', 'description' => 'Ajuste en Contribuciones a Cargo del Trabajador Pagadas por el Patrón Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '032', 'description' => 'Ajuste en Premios por puntualidad Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '033', 'description' => 'Ajuste en Prima de Seguro de vida Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '034', 'description' => 'Ajuste en Seguro de Gastos Médicos Mayores Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '035', 'description' => 'Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '036', 'description' => 'Ajuste en Subsidios por incapacidad Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '037', 'description' => 'Ajuste en Becas para trabajadores y/o hijos Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '038', 'description' => 'Ajuste en Horas extra Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '039', 'description' => 'Ajuste en Horas extra Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '040', 'description' => 'Ajuste en Prima dominical Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '041', 'description' => 'Ajuste en Prima dominical Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '042', 'description' => 'Ajuste en Prima vacacional Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '043', 'description' => 'Ajuste en Prima vacacional Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '044', 'description' => 'Ajuste en Prima por antigüedad Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '045', 'description' => 'Ajuste en Prima por antigüedad Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '046', 'description' => 'Ajuste en Pagos por separación Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '047', 'description' => 'Ajuste en Pagos por separación Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '048', 'description' => 'Ajuste en Seguro de retiro Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '049', 'description' => 'Ajuste en Indemnizaciones Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '050', 'description' => 'Ajuste en Indemnizaciones Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '051', 'description' => 'Ajuste en Reembolso por funeral Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '052', 'description' => 'Ajuste en Cuotas de seguridad social pagadas por el patrón Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '053', 'description' => 'Ajuste en Comisiones Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '054', 'description' => 'Ajuste en Vales de despensa Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '055', 'description' => 'Ajuste en Vales de restaurante Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '056', 'description' => 'Ajuste en Vales de gasolina Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '057', 'description' => 'Ajuste en Vales de ropa Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '058', 'description' => 'Ajuste en Ayuda para renta Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '059', 'description' => 'Ajuste en Ayuda para artículos escolares Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '060', 'description' => 'Ajuste en Ayuda para anteojos Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '061', 'description' => 'Ajuste en Ayuda para transporte Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '062', 'description' => 'Ajuste en Ayuda para gastos de funeral Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '063', 'description' => 'Ajuste en Otros ingresos por salarios Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '064', 'description' => 'Ajuste en Otros ingresos por salarios Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '065', 'description' => 'Ajuste en Jubilaciones, pensiones o haberes de retiro en una sola exhibición Exento ', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '066', 'description' => 'Ajuste en Jubilaciones, pensiones o haberes de retiro en una sola exhibición Gravado', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '067', 'description' => 'Ajuste en Pagos por separación Acumulable', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '068', 'description' => 'Ajuste en Pagos por separación No acumulable', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '069', 'description' => 'Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Exento', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '070', 'description' => 'Ajuste en Jubilaciones, pensiones o haberes de retiro en parcialidades Gravado', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '071', 'description' => 'Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador)', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '072', 'description' => 'Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento	2017-01-06', 'validity_start' => '2018-10-1', 'validity_end' => NULL],
			['id' => '073', 'description' => 'Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '074', 'description' => 'Ajuste en Alimentación Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '075', 'description' => 'Ajuste en Alimentación Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '076', 'description' => 'Ajuste en Habitación Exento', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '077', 'description' => 'Ajuste en Habitación Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '078', 'description' => 'Ajuste en Premios por asistencia', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '079', 'description' => 'Ajuste en Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados.', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '080', 'description' => 'Ajuste en Viáticos gravados', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '081', 'description' => 'Ajuste en Viáticos (entregados al trabajador)', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '082', 'description' => 'Ajuste en Fondo de ahorro Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '083', 'description' => 'Ajuste en Caja de ahorro Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '084', 'description' => 'Ajuste en Prima de Seguro de vida Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '085', 'description' => 'Ajuste en Seguro de Gastos Médicos Mayores Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '086', 'description' => 'Ajuste en Subsidios por incapacidad Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '087', 'description' => 'Ajuste en Becas para trabajadores y/o hijos Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '088', 'description' => 'Ajuste en Seguro de retiro Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '089', 'description' => 'Ajuste en Vales de despensa Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '090', 'description' => 'Ajuste en Vales de restaurante Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '091', 'description' => 'Ajuste en Vales de gasolina Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '092', 'description' => 'Ajuste en Vales de ropa Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '093', 'description' => 'Ajuste en Ayuda para renta Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '094', 'description' => 'Ajuste en Ayuda para artículos escolares Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '095', 'description' => 'Ajuste en Ayuda para anteojos Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '096', 'description' => 'Ajuste en Ayuda para transporte Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '097', 'description' => 'Ajuste en Ayuda para gastos de funeral Gravado', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '098', 'description' => 'Ajuste a ingresos asimilados a salarios gravados', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '099', 'description' => 'Ajuste a ingresos por sueldos y salarios gravados', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '100', 'description' => 'Ajuste en Viáticos exentos', 'validity_start' => '2017-01-06', 'validity_end' => NULL],
			['id' => '101', 'description' => 'ISR Retenido de ejercicio anterior', 'validity_start' => '2017-12-05', 'validity_end' => NULL],
			['id' => '102', 'description' => 'Ajuste a pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades, gravados', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '103', 'description' => 'Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de una resolución judicial o de un laudo gravados', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '104', 'description' => 'Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de una resolución judicial o de un laudo exentos', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '105', 'description' => 'Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de una resolución judicial o de un laudo gravados', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '106', 'description' => 'Ajuste a pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de una resolución judicial o de un laudo exentos', 'validity_start' => '2018-10-15', 'validity_end' => NULL],
			['id' => '107', 'description' => 'Ajuste al Subsidio Causado', 'validity_start' => '2020-01-01', 'validity_end' => NULL]
		];

		foreach ($deductions as $deduction)
		{
			App\CatDeduction::create($deduction);
		}
	}
}
