<?php

use Illuminate\Database\Seeder;

class ContractorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contractors = 
        [
            ['id' => '45', 'name' => '3M'],
            ['id' => '44', 'name' => 'AJAX'],
            ['id' => '50', 'name' => 'Ameristeel'],
            ['id' => '46', 'name' => 'BAYSA'],
            ['id' => '8', 'name' => 'Centurión '],
            ['id' => '64', 'name' => 'CFI construction'],
            ['id' => '28', 'name' => 'Comapa'],
            ['id' => '38', 'name' => 'COMAPA-JAGUAR'],
            ['id' => '12', 'name' => 'Consorcio / PDM '],
            ['id' => '5', 'name' => 'Consorcio Mariana'],
            ['id' => '15', 'name' => 'Construcciones Ferroviarias '],
            ['id' => '4', 'name' => 'Construcciones Garza'],
            ['id' => '30', 'name' => 'CR contratrista'],
            ['id' => '22', 'name' => 'Diaz Iga'],
            ['id' => '11', 'name' => 'ELVIC'],
            ['id' => '42', 'name' => 'Energy Control'],
            ['id' => '47', 'name' => 'FADISA'],
            ['id' => '16', 'name' => 'FOSMON'],
            ['id' => '43', 'name' => 'GCI'],
            ['id' => '7', 'name' => 'Gelapá Subestaciones'],
            ['id' => '61', 'name' => 'Geoglobal'],
            ['id' => '21', 'name' => 'Grupo Alejandro'],
            ['id' => '3', 'name' => 'Grupo PDM'],
            ['id' => '55', 'name' => 'Gumex'],
            ['id' => '63', 'name' => 'Hércules'],
            ['id' => '26', 'name' => 'Idinsa'],
            ['id' => '40', 'name' => 'Idinsa-Maquila-Jaguar'],
            ['id' => '14', 'name' => 'IEPSA'],
            ['id' => '18', 'name' => 'INMESI'],
            ['id' => '19', 'name' => 'J.A. DÍAZ Y CÍA S.A. DE C.V. / INMESI'],
            ['id' => '57', 'name' => 'JABC'],
            ['id' => '10', 'name' => 'Jaguar'],
            ['id' => '34', 'name' => 'Jimenéz y Flacón'],
            ['id' => '59', 'name' => 'JM Y CM construcciones'],
            ['id' => '31', 'name' => 'JPRH'],
            ['id' => '23', 'name' => 'Juan Carlos Fon / CRS '],
            ['id' => '33', 'name' => 'Kafer'],
            ['id' => '35', 'name' => 'Makila'],
            ['id' => '1', 'name' => 'Marsori / Delta'],
            ['id' => '29', 'name' => 'Meraver'],
            ['id' => '51', 'name' => 'Montgar'],
            ['id' => '13', 'name' => 'OH'],
            ['id' => '9', 'name' => 'OLP'],
            ['id' => '62', 'name' => 'OMEGA constructora.'],
            ['id' => '17', 'name' => 'Process Point'],
            ['id' => '54', 'name' => 'Proyecta'],
            ['id' => '60', 'name' => 'SERVINDLIZ'],
            ['id' => '53', 'name' => 'Sevilla fusion'],
            ['id' => '27', 'name' => 'Sindicato'],
            ['id' => '39', 'name' => 'SISTEM-Idinsa'],
            ['id' => '41', 'name' => 'SISTEN-Idinsa-Jaguar'],
            ['id' => '48', 'name' => 'Sisttemex'],
            ['id' => '6', 'name' => 'SMTELCOM'],
            ['id' => '2', 'name' => 'Tekkne'],
            ['id' => '36', 'name' => 'TRHR'],
            ['id' => '37', 'name' => 'TRHR-Idinsa'],
            ['id' => '56', 'name' => 'Turbomex'],
            ['id' => '52', 'name' => 'Valtic'],
            ['id' => '32', 'name' => 'Van Oord'],
            ['id' => '65', 'name' => 'Pemex'],
            ['id' => '66', 'name' => 'VAN OORD DE MÉXICO S.A. DE C.V.'],
            ['id' => '67', 'name' => 'INTEGRAL COMMISSIONING SERVICE SAS'],
            ['id' => '68', 'name' => 'DIAZ IGA EDIFICACIONES URBANAS E INDUSTRIALES, S.A DE C.V.'],
            ['id' => '69', 'name' => 'CONSTRUCTORA AZTECA DEL SURESTE, S.A. DE C.V.'],
            ['id' => '70', 'name' => 'CONSTRUCCIONES GARZA, S.A. DE C.V.'],
            ['id' => '71', 'name' => 'CORPORATIVO INDUSTRIAL Y SERVICIOS VELAZQUEZ, S.A. DE C.V.'],
            ['id' => '72', 'name' => 'IASSO CONSTRUCCIONES S.A. DE C.V.'],
            ['id' => '73', 'name' => 'OMEGA CONSTRUCTORA, S.A. DE C.V.'],
            ['id' => '74', 'name' => 'GERVEL CONSTRUCCIONES S.A.DE C.V.'],
            ['id' => '75', 'name' => 'FOSMON CONSTRUCCIONES, S.A. DE C.V.'],
            ['id' => '76', 'name' => 'COMERCIALIZADORA DE PRODUCTOS JIMENEZ Y FALCON S DE RL DE CV'],
            ['id' => '77', 'name' => 'JABC CONSTRUCCIONES Y SERVICIOS, S.A. DE C.V.'],
            ['id' => '78', 'name' => 'JAGUAR INGENIEROS CONSTRUCTORES, S.A. DE C.V.'],
            ['id' => '79', 'name' => 'MAKILA CONSTRUCCIONES, S. DE R.L. DE C.V.'],
            ['id' => '80', 'name' => 'COMERCIALIZADORA COMAPA, S.A. DE C.V.'],
            ['id' => '81', 'name' => 'CONSTRUCCIONES JM Y CM, S.A. DE C.V.'],
            ['id' => '82', 'name' => 'EIMEX SERVICIOS INTEGRALES, S.A. DE C.V.'],
            ['id' => '83', 'name' => 'SERVINDLIZ, S.A. DE C.V.'],
            ['id' => '84', 'name' => 'ALBE CONSTRUCTORA E INMOBILIARIA, S.A. DE C.V.'],
            ['id' => '85', 'name' => 'GRUPO GITCOM, S.A. DE C.V.'],
            ['id' => '86', 'name' => 'PROYECTOS INDUSTRIALES DE COATZACOALCOS, S.A. DE C.V.'],
            ['id' => '87', 'name' => 'INDUSTRIAL HERMET S.A. DE C.V.'],
            ['id' => '88', 'name' => 'CONSTRUCTORA KANINSA, S.A. DE C.V. '],
            ['id' => '89', 'name' => 'SEA DESARROLLO DE INFRAESTRUCTURA, S.A. DE C.V.'],
            ['id' => '90', 'name' => 'CONSTRUCTORA URBANIZADORA Y COMERCIALIZADORA HERCULES S.A. DE C.V.'],
            ['id' => '91', 'name' => 'DISTRIBUIDORA VASGA S.A. DE C.V.'],
            ['id' => '92', 'name' => 'HIDRO-TRABAJOS INDUSTRIALES DEL CENTRO (HIDROTIC)'],
            ['id' => '93', 'name' => 'SERVICIOS Y SUMINISTROS INDUSTRIALES ROCA, S.A. DE C.V.'],
            ['id' => '94', 'name' => 'MULTISERVICIOS ROCAMEX, S.A. DE C.V.'],
            ['id' => '95', 'name' => 'ENERGY & CONTROLS DE MEXICO, S.A. DE C.V.'],
            ['id' => '96', 'name' => 'SERVICIOS INTEGRALES DE INGENIERIA Y CONSULTORIA DE MEXICO, S.A. DE C.V.'],
            ['id' => '97', 'name' => 'SERVICIOS INTEGRALES DE TEAPA, S.A. DE C.V.'],
            ['id' => '98', 'name' => 'SYLVIA CASTAÑEDA PALMA'],
            ['id' => '99', 'name' => 'MANTENIMIENTO Y CONSTRUCCIONES MAY-MAT, S.A. DE C.V.'],
            ['id' => '100', 'name' => 'OZHAYEK Y HFRUIZ CONSTRUCCIONES, S.A. DE C.V.'],
            ['id' => '101', 'name' => 'CORPORATIVO ROLI, S.A. DE C.V.'],
            ['id' => '102', 'name' => 'INDUSTRIALIZACIONES GUMEX, S.A. DE C.V.'],
            ['id' => '103', 'name' => 'PROYECTOS Y CONSTRUCCIONES TABASCO VERDE, S.A. DE C.V.'],
            ['id' => '104', 'name' => 'INMOBILIARIA KAFER, S.A. DE C.V.'],
            ['id' => '105', 'name' => 'A&W LOGISTICS, S.A. DE C.V.'],
            ['id' => '106', 'name' => 'LMC SERVICIOS AMBIENTALES, S.A. DE C.V.'],
            ['id' => '107', 'name' => 'COATZAMEX, S.A. DE C.V.'],
            ['id' => '108', 'name' => 'CORPORATIVO G&G MEXICO – MAYA, S.A. DE C.V. '],
            ['id' => '109', 'name' => 'BARRERA ROCIEL, S.A. DE C.V.'],
            ['id' => '110', 'name' => 'COMERCIALIZADORA Y CONSTRUCTORA LIBRA, S.A. DE C.V.'],
            ['id' => '111', 'name' => 'SERVICIOS ESPECIALIZADOS TOPOGRAFIA Y BATIMETRIA'],
            ['id' => '112', 'name' => 'SEVILLA FUSION, S.A. DE C.V.'],
            ['id' => '113', 'name' => 'JUDITH ROSIQUE REYES'],
            ['id' => '114', 'name' => 'SIULZIL CONSTRUCCIONES'],
            ['id' => '115', 'name' => 'LAB SAPS LABORATORIO S.C.'],
            ['id' => '116', 'name' => 'RADIOGRAFIAS CABALLERO S.A. DE C.V.'],
            ['id' => '117', 'name' => 'STIN SISTEMAS TECNICOS INTERNACIONALES, S.A. DE C.V.'],
            ['id' => '118', 'name' => 'CONCEPTO FLEXIBLE EN INGENIERIA, S.A. DE C.V.'],
            ['id' => '119', 'name' => 'ANALISIS, CALIDAD Y ASESORIA INDUSTRIAL S.A. DE C.V.'],
            ['id' => '120', 'name' => 'COMERCIO Y CONSTRUCCION DE TABASCO, S.A. DE C.V.'],
            ['id' => '121', 'name' => 'ROMI INGENIERIA TOPOGRAFIA DE PRECISION Y RENTA DE EQUIPO'],
            ['id' => '122', 'name' => 'GRUPO VAZAV, S.A. DE C.V.'],
            ['id' => '123', 'name' => 'AMBULANCIAS MEDIS 7/24 RODRIGO RODRIGUEZ ROMERO'],
            ['id' => '124', 'name' => 'RIGOBERTO AGUIRRE HERNANDEZ CORRESPONSABLE EN SEGURIDAD ESTRUCTURAL'],
            ['id' => '125', 'name' => 'JOSE DICK GALLEGOS RAMOS UNIDAD DE INSPECCION DE INSTALACIONES ELECTRICAS']
        ];

        foreach($contractors as $contractor)
        {
            App\Contractor::create($contractor);
        }
    }
}
